name: env-model1
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy=1.21.2
  - pip=21.2.4
  - scipy=1.7.1
  - tensorflow=2.4.1
  - pip:
      - azureml-defaults==1.33.0
      - inference-schema[numpy-support]==1.3.0
      - joblib==1.0.1
